# Generated by Django 5.2.4 on 2025-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(default='042d36a1', max_length=8, unique=True),
        ),
    ]
