# Generated by Django 5.2.4 on 2025-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_trip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='code',
            field=models.CharField(default='79a2b012', max_length=8, unique=True),
        ),
    ]
