# Generated by Django 5.2.4 on 2025-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_expense_amount_alter_trip_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'أكل'), ('Transport', 'مواصلات'), ('Hotel', 'سكن'), ('Shopping', 'تسوق'), ('Entertainment', 'ترفيه'), ('Other', 'اخرى')], max_length=20),
        ),
    ]
